# Generated by Django 3.1.3 on 2020-11-19 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0003_auto_20201119_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora_turno',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 31, 20, 0)),
        ),
    ]
