# Generated by Django 3.1.3 on 2020-11-19 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0004_auto_20201119_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora_turno',
            field=models.TimeField(default=datetime.datetime(2000, 1, 31, 20, 0)),
        ),
    ]
