# Generated by Django 3.1.3 on 2020-11-19 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0005_auto_20201119_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha_turno',
            field=models.TimeField(default=datetime.datetime(2000, 1, 31, 20, 0)),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_turno',
            field=models.DateField(default=datetime.datetime(2000, 1, 31, 20, 0)),
        ),
    ]
