# Generated by Django 3.1.3 on 2020-11-19 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0006_auto_20201119_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_turno',
            field=models.TimeField(default=datetime.datetime(2000, 1, 31, 0, 0)),
        ),
    ]
