# Generated by Django 3.1.3 on 2020-11-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0007_auto_20201119_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='id_paciente',
        ),
    ]
