# Generated by Django 3.1.3 on 2020-11-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0008_remove_turno_id_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='turno',
        ),
    ]
