# Generated by Django 3.1.3 on 2020-11-19 22:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0009_delete_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno', models.TimeField(default=datetime.datetime(2000, 1, 31, 0, 0))),
                ('hora_turno', models.DateField(default=datetime.datetime(2000, 1, 31, 20, 0))),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_consultorio.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_consultorio.paciente')),
            ],
        ),
    ]
