# Generated by Django 3.1.3 on 2020-11-23 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0011_auto_20201120_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='historia_medica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2000, 1, 31, 0, 0))),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_consultorio.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_consultorio.paciente')),
            ],
        ),
    ]
