# Generated by Django 3.1.3 on 2020-11-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0012_historia_medica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_turno',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_turno',
            field=models.TimeField(),
        ),
    ]
