# Generated by Django 3.1.2 on 2020-11-26 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0014_historia_medica_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=64)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('clasificacion', models.CharField(choices=[('LENTE', 'lente'), ('ACCESORIO', 'accesorio'), ('ETC', 'etc')], max_length=32)),
                ('distacia_vision', models.CharField(max_length=10)),
                ('ojo_vision', models.CharField(choices=[('IZQUIERDO', 'izquierdo'), ('DERECHO', 'derecho')], max_length=32)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'pendiente'), ('FINALIZADO', 'finalizado')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(default=datetime.datetime(2000, 1, 31, 0, 0))),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_consultorio.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_consultorio.venta')),
            ],
        ),
    ]
