# Generated by Django 3.1.3 on 2020-11-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0017_auto_20201126_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_medica',
            name='fecha',
            field=models.DateField(),
        ),
    ]
