# Generated by Django 3.1.3 on 2020-11-26 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_consultorio', '0018_auto_20201126_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='forma_de_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'efectivo'), ('TARJETA DE CREDITO', 'tarjeta de credito'), ('DEBITO', 'debito'), ('BILLETERA VIRTUAL', 'billetera virtual')], max_length=32),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_User',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='total_vent',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='distacia_vision',
            field=models.CharField(choices=[('LEJOS', 'lejos'), ('CERCA', 'cerca')], max_length=10),
        ),
    ]
