# Generated by Django 3.1.3 on 2020-11-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0020_auto_20201127_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='venta_temporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_consultorio.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_consultorio.venta')),
            ],
        ),
    ]
