# Generated by Django 3.1.3 on 2020-11-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0021_venta_temporal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta_temporal',
            name='id_venta',
        ),
    ]
