# Generated by Django 3.1.2 on 2020-11-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0022_remove_venta_temporal_id_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'pendiente'), ('PEDIDO', 'pedido'), ('FINALIZADO', 'finalizado')], default='PENDIENTE', max_length=32),
        ),
    ]
