# Generated by Django 3.1.3 on 2020-11-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultorio', '0023_auto_20201128_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='id_venta',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='id_venta',
            field=models.ManyToManyField(to='gestion_consultorio.venta'),
        ),
    ]
